# Generated by Django 6.0.6 on 2026-07-07 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20260707_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='dummyuser',
            name='converted_back_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
